php_packages:
    - php7.0
    - php7.0-common
    - php7.0-cli
    - php7.0-curl
    - php7.0-mcrypt
    - php7.0-mysql
    - php7.0-gd
php_timezone: Europe/Paris
php_upload_max_filesize: "32M"
php_post_max_filesize: "32M"
php_memory_limit: "1024M"
